config/routes.rb
Rails.application.routes.draw do
  root 'web_scrappers#new'
  resources :web_scrapper

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scrapped_data.rb
class ScrappedData < ApplicationRecord
end

app/models/web_scrapper.rb
class WebScrapper < Kimurai::Base
  @name = 'vehicles_spider'
  @engine = :mechanize
  @start_urls = ["https://metaruby.com/"]
  @config = {
      user_agent: "Chrome/68.0.3440.84"
    }

  def parse(response, url:, data: { })
    response.xpath("//table[@class='topic-list']//tbody//tr").each do |tr|
      scrapped_data = {
                        title: tr.at('td[1]//span').text.strip,
                        category: tr.at('td[1]//div//span').text.strip,
                        date: tr.at('td[3]').text.strip
                      }
      ::ScrappedData.find_or_create_by(scrapped_data)                
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web_scrappers_controller.rb
class WebScrappersController < ApplicationController
  def index
  end

  def new
    @data = WebScrapper.crawl!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_scrappers_controller_helper.rb
module WebScrappersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicWebScrapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web_scrappers/index.html.erb
<%= link_to 'Start Scrap', new_web_scrapper_path %>

app/views/web_scrappers/new.html.erb
<%= @data %>